<a href="https://colab.research.google.com/github/ShFANI/FrauadDetection_CreditCard/blob/main/Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pytorch Tutorial Learning Codes**

In [1]:
import torch
import numpy as np

**Tensors**

In [3]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.5055,  0.9889,  0.5063, -0.4795],
        [-0.7358,  1.2544,  0.4682,  1.8862],
        [-1.9070, -1.0743, -1.4396, -0.4367]])

In [5]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.5922, 0.8251, 0.7936, 0.0559],
        [0.4048, 0.2332, 0.3005, 0.3933],
        [0.3266, 0.8683, 0.0294, 0.3864]])

In [4]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

**Create Tensor form Numpy Arrays**

In [13]:
np1 = np.random.rand(3,4)
np1

array([[0.47272819, 0.86349205, 0.28638163, 0.70215884],
       [0.71882411, 0.11000354, 0.18372118, 0.27437489],
       [0.11574521, 0.94082446, 0.47708564, 0.60528619]])

In [40]:
tensor_a**tensor_b

tensor([      1,     128,    6561,  262144, 9765625])

In [14]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4727, 0.8635, 0.2864, 0.7022],
        [0.7188, 0.1100, 0.1837, 0.2744],
        [0.1157, 0.9408, 0.4771, 0.6053]], dtype=torch.float64)

In [12]:
np1.dtype

dtype('float64')

In [11]:
import torch
my_torch = torch.arange(15)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
#reshape and view
my_torch = my_torch.reshape(2,5)
my_torch


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
# reshape if we don't know the number of items using -1
my_torch2 = my_torch.reshape(3, -1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [13]:
my_torch3 =  torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_torch5[0]=45
my_torch5

tensor([45,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [19]:
my_torch5[3]=90
my_torch5

tensor([45,  1,  2, 90,  4,  5,  6,  7,  8,  9])

In [26]:
my_torch8 = my_torch4.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [27]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [28]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [22]:
my_torch

tensor([ 0,  1,  2, 90,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
tensor_a=torch.tensor([1,2,3,4,5])
tensor_b=torch.tensor([6,7,8,9,10])

In [30]:
tensor_a+tensor_b

tensor([ 7,  9, 11, 13, 15])

In [32]:
torch.add(tensor_a, tensor_b)

tensor([ 7,  9, 11, 13, 15])

In [33]:
tensor_a *tensor_b

tensor([ 6, 14, 24, 36, 50])

In [34]:
torch.mul(tensor_a, tensor_b)

tensor([ 6, 14, 24, 36, 50])

In [35]:
tensor_b/tensor_a

tensor([6.0000, 3.5000, 2.6667, 2.2500, 2.0000])

In [36]:
torch.div(tensor_a, tensor_a)

tensor([1., 1., 1., 1., 1.])

In [37]:
tensor_b%tensor_a

tensor([0, 1, 2, 1, 0])

In [38]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 1, 2, 1, 0])

In [39]:
torch.pow(tensor_a, tensor_b)

tensor([      1,     128,    6561,  262144, 9765625])