<a href="https://colab.research.google.com/github/ShFANI/FrauadDetection_CreditCard/blob/main/Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pytorch Tutorial Learning Codes**

In [1]:
import torch
import numpy as np

**Tensors**

In [3]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.5055,  0.9889,  0.5063, -0.4795],
        [-0.7358,  1.2544,  0.4682,  1.8862],
        [-1.9070, -1.0743, -1.4396, -0.4367]])

In [5]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.5922, 0.8251, 0.7936, 0.0559],
        [0.4048, 0.2332, 0.3005, 0.3933],
        [0.3266, 0.8683, 0.0294, 0.3864]])

In [4]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

**Create Tensor form Numpy Arrays**

In [13]:
np1 = np.random.rand(3,4)
np1

array([[0.47272819, 0.86349205, 0.28638163, 0.70215884],
       [0.71882411, 0.11000354, 0.18372118, 0.27437489],
       [0.11574521, 0.94082446, 0.47708564, 0.60528619]])

In [12]:
np1.dtype

dtype('float64')